Update commands in user guide
AY2425S1-CS2103T-T13-1/tp pull request #57
Opened 2024-10-20 07:52 UTC by aldentantan

2024-10-20 13:56 UTC, Johnwz123 requested changes

2024-10-20 13:56 UTC, Johnwz123 commented on docs/UserGuide.md
> +| **Add**    | `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS ecname/EMERGENCY_CONTACT_NAME [t/TAG]…​` <br> e.g., `add n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665` <br> `ecn
Are the emergency contact fields and doctor fields compulsory?
Could you help add them to the command format also, right before the example?

2024-10-20 14:16 UTC, aldentantan commented on docs/UserGuide.md
> +| **Add**    | `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS ecname/EMERGENCY_CONTACT_NAME [t/TAG]…​` <br> e.g., `add n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665` <br> `ecn
Thanks for pointing that out! Emergency contact and doctor fields are compulsory.

2024-10-20 14:16 UTC, aldentantan commented on docs/UserGuide.md
> +| **Add**    | `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS ecname/EMERGENCY_CONTACT_NAME [t/TAG]…​` <br> e.g., `add n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665` <br> `ecn
Thanks for pointing that out! Emergency contact and doctor fields are compulsory.

2024-10-21 04:22 UTC, saajidshaik02 approved these changes
LGTM!

2024-10-21 04:23 UTC, saajidshaik02 approved these changes
LGTM!

2024-10-21 05:48 UTC, Johnwz123 approved these changes
LGTM. Thanks!

2024-10-21 05:48 UTC, merged