Addec command and more
AY2425S1-CS2103T-T13-1/tp pull request #75
Opened 2024-10-22 17:33 UTC by kellywsq03

Extend the add, edit and delete commands to support multiple emergency contacts

2024-10-22 17:38 UTC, kellywsq03 commented
Please don't merge yet, I'll fix the code coverage and comb for bugs

2024-10-23 02:18 UTC, Johnwz123 requested changes

2024-10-23 02:18 UTC, Johnwz123 commented on src/main/java/seedu/address/commons/core/index/Index.java
> +    }
Sorry. Could you explain the use of this nested class?

2024-10-23 03:21 UTC, kellywsq03 commented on src/main/java/seedu/address/commons/core/index/Index.java
> +    }
This class is used as a placeholder in parsing arguments the absence of an emergency contact index provided in the delete command.

As this introduces a fair bit of complexity, I aim to introduce an ec/ field in the delete command instead, such that this class may be removed.

2024-10-24 01:57 UTC, aldentantan commented on src/main/java/seedu/address/logic/commands/DeleteCommand.java
> +            + "Example: " + COMMAND_WORD + " 1 1";
Should the example message also include a `PREFIX_EMERGENCY_CONTACT_TO_EDIT` for the second integer?

2024-10-24 02:35 UTC, kellywsq03 commented on src/main/java/seedu/address/logic/commands/DeleteCommand.java
> +        model.setPerson(personToDelete, personToDelete);
It refreshes the address book to display the updated person!

2024-10-24 02:36 UTC, kellywsq03 commented on src/main/java/seedu/address/logic/commands/DeleteCommand.java
> +            + "Example: " + COMMAND_WORD + " 1 1";
Will add this in my next pull request. Thanks for the good catch!

2024-10-24 06:09 UTC, saajidshaik02 requested changes
Please see below

2024-10-24 07:23 UTC, kellywsq03 commented on src/main/java/seedu/address/ui/EmergencyContactCard.java
Great suggestion! Will add it to my next push :)

2024-10-24 07:25 UTC, kellywsq03 commented on src/main/java/seedu/address/logic/commands/AddEmergencyContactCommand.java
> +        Set<EmergencyContact> updatedEmergencyContacts = new LinkedHashSet<>(personToEditEmergencyContacts);
The Delete command operates on the index of the emergency contacts. A HashSet doesn't necessarily preserve the order of the elements, hence resulting in rogue outcomes during deletion. A LinkedHashSet preserves the order and hence provides predictable outcomes! Hope this helps!

2024-10-24 08:36 UTC, Johnwz123 approved these changes

2024-10-24 12:46 UTC, aldentantan approved these changes

2024-10-24 13:23 UTC, saajidshaik02 approved these changes
LGTM!

2024-10-24 13:45 UTC, merged