Add Find Doctor Command
AY2425S1-CS2103T-T13-1/tp pull request #76
Opened 2024-10-23 04:04 UTC by aldentantan

Added a command to filter users by their assigned doctors.

2024-10-23 04:07 UTC, aldentantan commented
Can merge after I address Codecov

2024-10-24 05:03 UTC, aldentantan commented
Closes #76

2024-10-24 06:09 UTC, saajidshaik02 requested changes
Please see below

2024-10-24 06:17 UTC, saajidshaik02 requested changes
Please see below

2024-10-24 06:17 UTC, saajidshaik02 commented on docs/UserGuide.md
> +
Good use of image for the userguide!

2024-10-24 07:32 UTC, kellywsq03 requested changes

2024-10-24 07:32 UTC, kellywsq03 commented on docs/UserGuide.md
> +  ![result for 'finddoc tan ed'](images/finddoc-tan-ed.png)
You may want to update this image when the UI for the EmergencyContacts is updated!

2024-10-24 07:32 UTC, kellywsq03 commented on src/main/java/seedu/address/model/person/DoctorNameContainsKeywordsPredicate.java
> +        return keywords.stream()
Duper succinct code! Brought tears to my eyes :)

2024-10-24 07:32 UTC, kellywsq03 commented on src/test/java/seedu/address/logic/parser/FindDoctorCommandParserTest.java
> +        // multiple whitespaces between keywords
Helpful comments for developers!

2024-10-24 09:05 UTC, aldentantan commented on docs/UserGuide.md
> +  ![result for 'finddoc tan ed'](images/finddoc-tan-ed.png)
Will remember to update once all the PR's are merged, thanks!

2024-10-24 12:04 UTC, kellywsq03 approved these changes

2024-10-24 13:23 UTC, saajidshaik02 approved these changes
LGTM!

2024-10-24 13:30 UTC, merged