Add commands to load and list all archive files
AY2425S1-CS2103T-T13-1/tp pull request #77
Opened 2024-10-23 04:30 UTC by Johnwz123

Closes #62 and #63 

### List all archive files
Enter the command `listArchives` to list all archive filenames in the CLI.
If there are no archive files, it should return the message "No archive files found."

### Load archive file
Enter the command `loadArchive [FILENAME]` to load the respective archive file.

2024-10-23 12:13 UTC, aldentantan commented on src/main/java/seedu/address/logic/commands/ListArchiveFilesCommand.java
> +    private static final Logger logger = LogsCenter.getLogger(ListArchiveFilesCommand.class);
The private variable should be declared after the public variables, following checkstyle.

2024-10-23 12:14 UTC, aldentantan commented on src/main/java/seedu/address/logic/commands/LoadArchiveCommand.java
> +    private static final Logger logger = LogsCenter.getLogger(LoadArchiveCommand.class);
Same comment as above, declare the private variable after all the public variables.

2024-10-24 06:13 UTC, saajidshaik02 requested changes
Please see below

2024-10-24 06:13 UTC, saajidshaik02 commented on src/main/java/seedu/address/logic/commands/ListArchiveFilesCommand.java
> +            for (Path entry : stream) {
Good use of streams!

2024-10-24 06:13 UTC, saajidshaik02 commented on src/main/java/seedu/address/logic/commands/LoadArchiveCommand.java
> +        assert source != null : "Address book file path is null";
Codecov / codecov/patch not covered, please do test for these cases!

2024-10-24 07:39 UTC, kellywsq03 requested changes
Great work!

2024-10-24 07:39 UTC, kellywsq03 commented on src/test/java/seedu/address/logic/commands/ArchiveCommandTest.java
> +        Files.walk(new ModelManager().getAddressBookFilePath().getParent())
Great use of method chaining. Keep up the good work.

2024-10-24 07:39 UTC, kellywsq03 commented on src/test/java/seedu/address/logic/commands/ListArchiveFilesCommandTest.java
> +    @EnabledOnOs({OS.WINDOWS, OS.LINUX})
Will you be extended support to other platforms as well? What are the blockers?

2024-10-24 07:39 UTC, kellywsq03 commented on src/main/java/seedu/address/logic/commands/LoadArchiveCommand.java
> +            + "Example: " + COMMAND_WORD + "addressbook-20241023_114324-example.json";
I apologize if this is a strange request as I'm unfamiliar with how the json files are named, but is it possible for the naming convention to be more user friendly? eg consistent dd/mm/yy format?

2024-10-24 08:32 UTC, Johnwz123 commented on src/main/java/seedu/address/logic/commands/LoadArchiveCommand.java
> +            + "Example: " + COMMAND_WORD + "addressbook-20241023_114324-example.json";
Noted. Have created an issue for it #79 
"20241023_114324" is the timestamp and "example" is the custom name FYI.

2024-10-24 08:32 UTC, Johnwz123 commented on src/test/java/seedu/address/logic/commands/ArchiveCommandTest.java
> +        Files.walk(new ModelManager().getAddressBookFilePath().getParent())
As discussed over Telegram.

2024-10-24 12:03 UTC, kellywsq03 approved these changes
LGTM :D

2024-10-24 12:47 UTC, aldentantan approved these changes

2024-10-24 13:22 UTC, saajidshaik02 approved these changes
LGTM!

2024-10-24 13:29 UTC, merged