Add Autocomplete feature
AY2425S1-CS2103T-T13-1/tp pull request #78
Opened 2024-10-23 12:23 UTC by saajidshaik02

Closes #60

2024-10-23 12:53 UTC, kellywsq03 requested changes
Fantastic work Saajid! You truly are a talented developer.

2024-10-23 12:53 UTC, kellywsq03 commented on src/main/java/seedu/address/ui/CommandBox.java
> +     * Creates a CommandBox with the given CommandExecutor.
You may want to follow the JavaDoc conventions by using formatted text for classes in the comment!

2024-10-23 12:53 UTC, kellywsq03 commented on src/main/java/seedu/address/ui/CommandBox.java
> +     */
Consider using {@param } and {@return } tags in your JavaDoc headers!

2024-10-23 12:53 UTC, kellywsq03 commented on src/main/java/seedu/address/ui/CommandBox.java
> +     */
As in my comment above, consider highlighting the parameters in your JavaDoc headers for easy scanning!

2024-10-23 12:53 UTC, kellywsq03 commented on src/main/java/seedu/address/ui/CommandBox.java
> +     * Extracts the parameter description from the full syntax
Consider using ChatGPT for your JavaDoc headers!

2024-10-23 12:53 UTC, kellywsq03 commented on src/main/java/seedu/address/ui/CommandBox.java
> +        // Handle space and tab press for completion
Great use of handy notes for developers to easily understand your code!

2024-10-24 01:43 UTC, aldentantan commented on src/main/java/seedu/address/ui/CommandBox.java
> +            //Since "p/" is alr present but there’s no / after 9876, it identifies the user is working on the p/ param
Nice explanation of the autocomplete feature! This would be good to include in the Developer Guide

2024-10-24 01:44 UTC, aldentantan commented on src/main/java/seedu/address/ui/CommandBox.java
> +     * Extracts the parameter description from the full syntax
Github Copilot also gives suggestions on the recommended Javadoc format

2024-10-24 12:02 UTC, kellywsq03 approved these changes
LGTM!

2024-10-24 13:24 UTC, merged